import { readFile, mkdir, writeFile, cp, rm } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import path from 'node:path';

const root = fileURLToPath(new URL('..', import.meta.url));
const out = path.join(root, '_site');
const config = JSON.parse(await readFile(path.join(root, 'site.config.json'), 'utf8'));
const esc = s => String(s).replace(/[&<>"']/g, c => ({ '&':'&amp;', '<':'&lt;', '>':'&gt;', '"':'&quot;', "'":'&#39;' }[c]));
const email = config.supportEmail;
const operatorName = typeof config.operatorName === 'string' ? config.operatorName.trim() : '';
if (config.privacyReviewed && !operatorName) throw Error('Reviewed policy requires the actual operator name');
if (email && !/^[\w.+-]+@[\w.-]+\.[a-z]{2,}$/i.test(email)) throw Error('Invalid supportEmail');
if (config.appStoreUrl && !/^https:\/\/apps\.apple\.com\//.test(config.appStoreUrl)) throw Error('Use an official App Store URL');
if (config.adMobPublisherId && !/^pub-\d{16}$/.test(config.adMobPublisherId)) throw Error('Invalid AdMob publisher ID');
if (config.origin !== 'https://haiyuestudio.github.io') throw Error('Update the canonical origin deliberately before changing domains');
const contact = email ? `<a href="mailto:${esc(email)}">${esc(email)}</a>` : 'Support contact will be announced before launch.';
const store = config.appStoreUrl ? `<a class="button" href="${esc(config.appStoreUrl)}">View on the App Store <span aria-hidden="true">↗</span></a>` : '<span class="pill">Coming to iOS</span>';
const eyebrow = s => `<div class="eyebrow"><span class="dot" aria-hidden="true"></span>${s}</div>`;
const shot = '<img src="/assets/calendar-puzzle.png" width="1864" height="860" alt="Calendar Puzzle: colorful puzzle pieces beside a calendar board, with September, 22 and Tuesday highlighted." decoding="async">';
const pages = [];
function page(url, title, description, content) {
  pages.push({ url, title });
  return `<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>${esc(title)} · Haiyue Studio</title><meta name="description" content="${esc(description)}"><meta name="theme-color" content="#080c18"><link rel="canonical" href="${config.origin}${url}"><meta property="og:type" content="website"><meta property="og:title" content="${esc(title)} · Haiyue Studio"><meta property="og:description" content="${esc(description)}"><meta property="og:url" content="${config.origin}${url}"><meta property="og:image" content="${config.origin}/assets/calendar-puzzle.png"><link rel="icon" type="image/png" href="/assets/haiyue-moon.png"><link rel="stylesheet" href="/assets/site.css"></head>
<body><a class="skip" href="#main">Skip to content</a><div class="wrap"><header class="header"><a class="brand" href="/" aria-label="Haiyue Studio home"><img src="/assets/haiyue-moon.png" alt="" width="39" height="39">Haiyue Studio</a><nav class="nav" aria-label="Main navigation"><a href="/calendar-puzzle/" ${url==='/calendar-puzzle/'?'aria-current="page"':''}>Our game</a><a class="about-link" href="/#studio">Studio</a><a href="/support/" ${url==='/support/'?'aria-current="page"':''}>Support</a></nav></header>
<main id="main">${content}</main><footer class="footer"><span>© ${config.policyUpdated.slice(0,4)} Haiyue Studio. Made with curiosity.</span><div class="footer-links"><a href="/calendar-puzzle/">Calendar Puzzle</a><a href="/privacy/">Privacy</a><a href="/support/">Support</a></div></footer></div></body></html>`;
}
const files = new Map();
files.set('index.html', page('/', 'Small games. A little discovery.', 'Thoughtfully made independent games. Discover Calendar Puzzle, a colorful daily challenge from Haiyue Studio.', `
<section class="hero"><div>${eyebrow('Independent games, thoughtfully made')}<h1>Small games.<br>A little <em>discovery.</em></h1><p class="lead">A new way to look at an ordinary day. We make playful worlds and satisfying little challenges, one detail at a time.</p><div class="actions"><a class="button" href="/calendar-puzzle/">Meet Calendar Puzzle <span aria-hidden="true">↗</span></a><a class="text-link" href="#studio">About the studio</a></div></div><div class="hero-art" aria-hidden="true"><span class="tile one"></span><span class="tile two"></span><span class="tile three"></span><img class="moon" src="/assets/haiyue-moon.png" width="384" height="384" alt=""><span class="art-label">Haiyue · a world of little wonders</span></div></section>
<section class="section" aria-labelledby="game-heading"><div class="section-heading"><div>${eyebrow('Our first chapter')}<h2 id="game-heading">Make today fit.</h2></div><p>A calendar. Colorful pieces. A fresh perspective.</p></div><article class="game-card"><div class="card-top"><div><span class="tag">Daily puzzle · Logic · Spatial thinking</span><h3>Calendar Puzzle</h3><p>Turn a date into a small, satisfying discovery.</p></div><a class="button" href="/calendar-puzzle/">Explore the game <span aria-hidden="true">→</span></a></div><div class="game-image">${shot}</div></article></section>
<section id="studio" class="section"><div class="section-heading"><div>${eyebrow('The studio')}<h2>Built around the joy of play.</h2></div></div><div class="features"><article class="feature"><span class="number">01</span><h3>A simple beginning</h3><p>Easy to understand, with room to experiment. Find the unexpected in a familiar idea.</p></article><article class="feature"><span class="number">02</span><h3>Care in the details</h3><p>Clear visuals, responsive controls, and those little moments when everything clicks into place.</p></article><article class="feature"><span class="number">03</span><h3>A little, every day</h3><p>Games that leave space for your day. Come back for a new challenge, at your own pace.</p></article></div></section>
<aside class="closing"><div><h2>Let’s make it better, together.</h2><p>Have a question, a thought, or a puzzle that has you stumped?</p></div><a class="button" href="/support/">Get in touch <span aria-hidden="true">↗</span></a></aside>`));

files.set('calendar-puzzle/index.html', page('/calendar-puzzle/', 'Calendar Puzzle', 'Arrange, rotate and flip colorful pieces to leave the month, day and weekday uncovered. A daily calendar puzzle for iOS.', `
<section class="page-hero">${eyebrow('A new date. A new challenge.')}<h1>Every day has<br>its <em>perfect fit.</em></h1><p class="lead">Arrange colorful pieces on a calendar board. Cover every square except the month, day, and weekday of your chosen date.</p><div class="actions">${store}<a class="text-link" href="#how-to-play">How to play ↓</a></div><p class="languages">English · 中文 · 日本語 · Français · Deutsch · Español</p></section><figure class="product-shot" style="margin-left:0;margin-right:0">${shot}<figcaption class="small" style="margin:12px 8px 0">An actual in-game view. Full-version controls shown.</figcaption></figure>
<section id="how-to-play" class="section"><div class="section-heading"><h2>A few pieces.<br>So many possibilities.</h2></div><div class="features"><article class="feature"><span class="number">01 / Arrange</span><h3>Find a place to start</h3><p>Drag a piece from the tray onto the calendar. Every piece has its own shape and a place in the solution.</p></article><article class="feature"><span class="number">02 / Explore</span><h3>Turn it around</h3><p>Rotate and flip pieces to try new combinations. Double-tap a piece to rotate it, or use the toolbar.</p></article><article class="feature"><span class="number">03 / Discover</span><h3>Leave your date visible</h3><p>Fit all pieces without covering your month, day, or weekday. Solve without a hint to earn a star in your history.</p></article></div></section>
<section class="section"><div class="section-heading"><h2>Your daily ritual.<br>Your choice to explore more.</h2></div><div class="plans"><article class="plan"><div class="eyebrow">Daily play</div><h3>Start with today.</h3><ul><li>Play the current date’s puzzle for free.</li><li>Get one free hint each day.</li><li>Choose to watch a rewarded ad for an extra hint, when available. Up to two ad rewards per day.</li><li>Keep a local record of your completed dates.</li></ul></article><article class="plan full"><div class="eyebrow">One-time full unlock</div><h3>Open the whole calendar.</h3><ul><li>Choose any date from the calendar.</li><li>Use unlimited hints.</li><li>Play without ads.</li><li>Restore your purchase using the same Apple Account.</li></ul><p class="small">No subscription. The purchase screen shows your local App Store price before you confirm.</p></article></div></section>
<aside class="closing"><div><h2>A little guidance goes a long way.</h2><p>Find answers about hints, progress, and restoring a purchase.</p></div><a class="button" href="/support/">Visit support <span aria-hidden="true">↗</span></a></aside>`));

files.set('support/index.html', page('/support/', 'Player support', 'Help with Calendar Puzzle controls, hints, purchases, progress and privacy. Contact Haiyue Studio.', `
<section class="page-hero">${eyebrow('Here to help')}<h1>Back to<br><em>the good part.</em></h1><p class="lead">A few answers to keep you playing. If something still doesn’t fit, get in touch.</p></section><div class="doc-layout"><nav class="toc" aria-label="Support topics"><a href="#contact">Contact us</a><a href="#playing">Playing & hints</a><a href="#purchases">Purchases</a><a href="#progress">Progress & privacy</a></nav><div class="prose"><section id="contact"><h2>Contact Haiyue Studio</h2><div class="contact"><strong>Game support & privacy requests</strong><br>${contact}</div><p>Please include your device model, iOS version, game version, and what happened. A screenshot can help, but remove personal information first. Never send passwords, verification codes, or full payment details.</p></section>
<section id="playing"><h2>Playing & hints</h2><details><summary>What am I trying to uncover?</summary><p>Leave the selected month, day number, and weekday visible. Cover all other calendar squares with the puzzle pieces, without overlaps.</p></details><details><summary>How do I rotate or flip a piece?</summary><p>Select a piece, then use the rotate or flip button in the toolbar. You can also double-tap a piece to rotate it. Drag a piece to move it.</p></details><details><summary>How do free hints and rewarded ads work?</summary><p>Free players receive one hint each local calendar day. After that, you can choose to watch an available rewarded ad for one extra hint, up to two ad rewards per day. A hint is charged only when a useful result is ready. Full-version players have unlimited hints.</p></details><details><summary>Why is there no ad available?</summary><p>Availability depends on your network, region, privacy choices, and ad inventory. You can keep playing without watching an ad. Closing an ad before its reward is earned does not grant a hint or use up an earned-ad reward slot.</p></details><details><summary>Why does a completed date have no star?</summary><p>Completing a puzzle records the date. The star is awarded only when you solve that puzzle without using hints, including free and ad-supported hints.</p></details></section>
<section id="purchases"><h2>Purchases</h2><details><summary>What does the full version unlock?</summary><p>The one-time purchase unlocks any calendar date and unlimited hints, with no ads. There is no subscription. Check the purchase screen for the current localized price.</p></details><details><summary>How do I restore my purchase?</summary><p>Use the same Apple Account that made the purchase. Connect to the internet, open the game’s settings and purchase panel, then choose Restore Purchases. Complete any Apple authentication request. Restoring a valid existing purchase does not buy it again.</p></details><details><summary>I purchased, but the game still shows the free version.</summary><p>Check that Apple completed the payment and that you are using the purchasing Apple Account. Reconnect to the internet and try Restore Purchases. Pending or cancelled transactions do not unlock the game. If the issue continues, email us with the error message.</p></details><details><summary>How can I request a refund?</summary><p>Apple handles App Store payments and refund requests. Visit <a href="https://reportaproblem.apple.com/">Apple’s Report a Problem page</a>. If Apple refunds or revokes a purchase, the full-version entitlement may be removed.</p></details></section>
<section id="progress"><h2>Progress & privacy</h2><details><summary>Where is my progress saved?</summary><p>Puzzles, completion history, language preferences and hint balances are saved locally on your device. The game does not provide its own account-based cloud sync. Deleting the app or its data can erase this progress; restoring a purchase restores access, not puzzle history.</p></details><details><summary>Can I change my advertising privacy choices?</summary><p>When required by the advertising consent system, an advertising privacy option appears in the game’s settings. Open it to review or change your choices. Read our <a href="/privacy/">Privacy Policy</a> for details about the game and this website.</p></details></section></div></div>`));

files.set('privacy/index.html', page('/privacy/', 'Privacy Policy', 'How Haiyue Studio handles Calendar Puzzle local data, Apple purchases, optional rewarded ads, support requests and website visits.', `
<section class="page-hero">${eyebrow('Your information, explained')}<h1>Privacy,<br><em>in plain words.</em></h1><p class="lead">Privacy Policy for Calendar Puzzle on iOS and the Haiyue Studio website.</p><p class="small">Last updated: ${esc(config.policyUpdated)}</p></section><div class="doc-layout"><nav class="toc" aria-label="Privacy sections"><a href="#overview">Overview</a><a href="#local">Game data</a><a href="#payments">Purchases</a><a href="#ads">Optional advertising</a><a href="#website">Website & support</a><a href="#choices">Your choices</a><a href="#children">Children</a><a href="#contact">Contact</a></nav><article class="prose">
${config.privacyReviewed?'':'<div class="notice"><strong>Pre-release policy draft.</strong> The advertising service is still being configured. This policy must be checked against the final release configuration before store submission.</div>'}
<h2 id="overview">1. Who we are</h2><p>${operatorName ? `${esc(operatorName)} is the individual developer operating under the name Haiyue Studio and is responsible for the personal information handled by us as described in this policy.` : 'Haiyue Studio develops Calendar Puzzle.'} This policy explains the information used by Calendar Puzzle on iOS, its service providers, and this website. You do not need to create a Haiyue account to play. For privacy requests, contact ${contact}.</p>
<h2 id="local">2. Information stored on your device</h2><p>The game stores your puzzle state, completed dates and stars, language preferences, hint allowances, rewarded hint credits, and purchase entitlement state locally. We do not operate a server that uploads or synchronizes your puzzle progress.</p><p>The current date is used to select the daily puzzle and refresh daily hint allowances. The game does not request access to your personal calendar, contacts, photos, microphone, or precise location. Local data remains until you remove it or the app; operating-system backup and restore behavior is controlled by your device settings.</p>
<h2 id="payments">3. Purchases through Apple</h2><p>Apple processes the optional, non-consumable full-version purchase. The game uses StoreKit to obtain product information and verify purchase, restoration, refund, and revocation status. Relevant product and transaction information and entitlement state are used to provide paid features and prevent invalid unlocks. We do not receive your payment card number or Apple Account password.</p><p>Apple handles its own transaction records under the <a href="https://www.apple.com/legal/privacy/">Apple Privacy Policy</a>. Restoring a purchase does not restore your local puzzle history.</p>
<h2 id="ads">4. Optional rewarded advertisements</h2><p>Free players can choose to watch a Google AdMob rewarded advertisement to receive an extra hint. We do not automatically play ads between puzzles. Full-version users do not need to watch ads.</p><p>When advertising services are used, Google’s Mobile Ads SDK and User Messaging Platform may process IP addresses (including approximate location derived from them), device or app identifiers, ad impressions and interactions, performance and crash information, and consent choices. These are used for ad delivery, measurement, fraud prevention, diagnostics, and privacy-choice management. The exact processing depends on region, consent, platform permissions, and SDK configuration.</p><p>Our ad requests are configured as non-personalized. This does not mean that no data is processed. The app does not currently request Apple’s App Tracking Transparency permission. Where required, Google’s consent form is presented before eligible ad requests; you can review applicable choices through the advertising privacy option in settings. Declining an ad or not granting consent does not prevent ordinary puzzle play.</p><p>Read <a href="https://policies.google.com/privacy">Google’s Privacy Policy</a>, <a href="https://policies.google.com/technologies/partner-sites">how Google uses information from partner apps</a>, and <a href="https://developers.google.com/admob/ios/privacy/data-disclosure">Google’s iOS advertising SDK data disclosure</a>. Google controls retention of the data it processes under its applicable policies.</p>
<h2 id="website">5. Website visits and support</h2><p>This website is hosted on GitHub Pages. We do not add advertising, analytics scripts, tracking cookies, or third-party fonts to these pages. GitHub may log visitor IP addresses for security, including for visitors who are not signed in. See the <a href="https://docs.github.com/en/site-policy/privacy-policies/github-general-privacy-statement">GitHub Privacy Statement</a>.</p><p>If you email us, we receive your email address and any information you include. We use it to respond, investigate the issue, and handle privacy requests. Please share only what is needed. Support correspondence is retained as needed to resolve the request and meet applicable obligations, and may be processed by our email provider. We do not use support messages for advertising.</p><p>Apple, Google, GitHub and email services may process data in countries other than your own, under their respective policies and applicable safeguards. No internet or storage system can be guaranteed completely secure.</p>
<h2 id="choices">6. Your choices and requests</h2><p>You can decline rewarded ads, review available consent options in game settings, manage permissions through iOS, or remove the app and its local data. When the advertising privacy option is available, use it to change or withdraw your advertising consent. Withdrawing consent does not affect processing that lawfully took place before withdrawal. You can continue ordinary puzzle play without agreeing to personalized advertising or watching rewarded ads.</p><p>To remove local progress, delete the app and its data from your device; offloading the app may keep its data. An operating-system backup may retain a copy according to your settings. This does not cancel or refund your Apple purchase or erase records held by Apple or Google.</p><p>Depending on your location, you may have rights to access, correct, delete, restrict or object to processing of your personal information, request portability, withdraw consent, or complain to your local data protection authority. Consent-based processing relies on your consent; purchase and support processing is used to provide requested services, and security processing supports legitimate security interests, subject to applicable law.</p><p>Email ${contact} to exercise rights concerning information we hold, including support correspondence. Tell us what you would like to access, correct or delete. We may request only the information reasonably needed to verify and handle your request, and may retain information where required by law. Do not send passwords or payment card details. For provider-held data, use the provider’s privacy controls or contact channels linked above. We do not hold your local puzzle history remotely and cannot retrieve or erase it on your device.</p>
<h2 id="children">7. Children</h2><p>Calendar Puzzle is a general-audience puzzle game and is not specifically directed to children under 13. We do not knowingly solicit personal information from children under 13. If you believe a child has sent us personal information, contact us so that we can investigate and take appropriate action. Parents and guardians can manage purchases and device access through Apple’s parental controls.</p>
<h2>8. Changes to this policy</h2><p>We may update this policy as the game or its services change. The date at the top identifies the latest version. Where required, we will provide additional notice or request consent for material changes.</p>
<h2 id="contact">9. Contact</h2><p>For support or privacy questions, contact Haiyue Studio at ${contact}.</p></article></div>`));
files.set('404.html', page('/404.html', 'Page not found', 'Find your way back to Haiyue Studio.', '<section class="error-page">'+eyebrow('404 · A piece out of place')+'<h1>Let’s find<br><em>your way back.</em></h1><p class="lead">This page may have moved, or the link may be incomplete.</p><a class="button" href="/">Back to the studio →</a></section>'));
await rm(out, { recursive:true, force:true });
await mkdir(out, { recursive:true });
await cp(path.join(root, 'assets'), path.join(out, 'assets'), { recursive:true });
for (const [file, html] of files) { await mkdir(path.dirname(path.join(out,file)), {recursive:true}); await writeFile(path.join(out,file), html); }
await writeFile(path.join(out,'.nojekyll'), '');
await writeFile(path.join(out,'app-ads.txt'), config.adMobPublisherId
  ? `google.com, ${config.adMobPublisherId}, DIRECT, f08c47fec0942fa0\n`
  : '# Advertising authorization pending. No production publisher ID has been configured.\n');
await writeFile(path.join(out,'robots.txt'), `User-agent: *\nAllow: /\nSitemap: ${config.origin}/sitemap.xml\n`);
await writeFile(path.join(out,'sitemap.xml'), '<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">'+pages.filter(p=>p.url!='/404.html').map(p=>`<url><loc>${config.origin}${p.url}</loc></url>`).join('')+'</urlset>\n');
console.log(`Built ${files.size} pages in _site. Contact: ${email ? 'configured' : 'missing'}. AdMob: ${config.adMobPublisherId ? 'configured' : 'pending'}. Privacy review: ${config.privacyReviewed ? 'confirmed' : 'pending'}.`);
